package snhttp.experimental.openssl.libssl.internal

import _root_.scala.scalanative.unsafe.*
import _root_.scala.scalanative.unsigned.*
import _root_.scala.scalanative.libc.*
import _root_.scala.scalanative.*

object enumerations:
  private[enumerations] trait _BindgenEnumCUnsignedInt[T](using eq: T =:= CUnsignedInt):
    given Tag[T] = Tag.UInt.asInstanceOf[Tag[T]]
    extension (inline t: T)
      inline def value: CUnsignedInt = eq.apply(t)
      inline def int: CInt = eq.apply(t).toInt
      inline def uint: CUnsignedInt = eq.apply(t)

  /**
   * [bindgen] header: /usr/include/openssl/ssl.h
   */
  opaque type OSSL_HANDSHAKE_STATE = CUnsignedInt
  object OSSL_HANDSHAKE_STATE extends _BindgenEnumCUnsignedInt[OSSL_HANDSHAKE_STATE]:
    given _tag: Tag[OSSL_HANDSHAKE_STATE] = Tag.UInt
    inline def define(inline a: Long): OSSL_HANDSHAKE_STATE = a.toUInt
    val TLS_ST_BEFORE = define(0)
    val TLS_ST_OK = define(1)
    val DTLS_ST_CR_HELLO_VERIFY_REQUEST = define(2)
    val TLS_ST_CR_SRVR_HELLO = define(3)
    val TLS_ST_CR_CERT = define(4)
    val TLS_ST_CR_COMP_CERT = define(5)
    val TLS_ST_CR_CERT_STATUS = define(6)
    val TLS_ST_CR_KEY_EXCH = define(7)
    val TLS_ST_CR_CERT_REQ = define(8)
    val TLS_ST_CR_SRVR_DONE = define(9)
    val TLS_ST_CR_SESSION_TICKET = define(10)
    val TLS_ST_CR_CHANGE = define(11)
    val TLS_ST_CR_FINISHED = define(12)
    val TLS_ST_CW_CLNT_HELLO = define(13)
    val TLS_ST_CW_CERT = define(14)
    val TLS_ST_CW_COMP_CERT = define(15)
    val TLS_ST_CW_KEY_EXCH = define(16)
    val TLS_ST_CW_CERT_VRFY = define(17)
    val TLS_ST_CW_CHANGE = define(18)
    val TLS_ST_CW_NEXT_PROTO = define(19)
    val TLS_ST_CW_FINISHED = define(20)
    val TLS_ST_SW_HELLO_REQ = define(21)
    val TLS_ST_SR_CLNT_HELLO = define(22)
    val DTLS_ST_SW_HELLO_VERIFY_REQUEST = define(23)
    val TLS_ST_SW_SRVR_HELLO = define(24)
    val TLS_ST_SW_CERT = define(25)
    val TLS_ST_SW_COMP_CERT = define(26)
    val TLS_ST_SW_KEY_EXCH = define(27)
    val TLS_ST_SW_CERT_REQ = define(28)
    val TLS_ST_SW_SRVR_DONE = define(29)
    val TLS_ST_SR_CERT = define(30)
    val TLS_ST_SR_COMP_CERT = define(31)
    val TLS_ST_SR_KEY_EXCH = define(32)
    val TLS_ST_SR_CERT_VRFY = define(33)
    val TLS_ST_SR_NEXT_PROTO = define(34)
    val TLS_ST_SR_CHANGE = define(35)
    val TLS_ST_SR_FINISHED = define(36)
    val TLS_ST_SW_SESSION_TICKET = define(37)
    val TLS_ST_SW_CERT_STATUS = define(38)
    val TLS_ST_SW_CHANGE = define(39)
    val TLS_ST_SW_FINISHED = define(40)
    val TLS_ST_SW_ENCRYPTED_EXTENSIONS = define(41)
    val TLS_ST_CR_ENCRYPTED_EXTENSIONS = define(42)
    val TLS_ST_CR_CERT_VRFY = define(43)
    val TLS_ST_SW_CERT_VRFY = define(44)
    val TLS_ST_CR_HELLO_REQ = define(45)
    val TLS_ST_SW_KEY_UPDATE = define(46)
    val TLS_ST_CW_KEY_UPDATE = define(47)
    val TLS_ST_SR_KEY_UPDATE = define(48)
    val TLS_ST_CR_KEY_UPDATE = define(49)
    val TLS_ST_EARLY_DATA = define(50)
    val TLS_ST_PENDING_EARLY_DATA_END = define(51)
    val TLS_ST_CW_END_OF_EARLY_DATA = define(52)
    val TLS_ST_SR_END_OF_EARLY_DATA = define(53)
    def getName(value: OSSL_HANDSHAKE_STATE): Option[String] =
      value match
        case `TLS_ST_BEFORE`                   => Some("TLS_ST_BEFORE")
        case `TLS_ST_OK`                       => Some("TLS_ST_OK")
        case `DTLS_ST_CR_HELLO_VERIFY_REQUEST` => Some("DTLS_ST_CR_HELLO_VERIFY_REQUEST")
        case `TLS_ST_CR_SRVR_HELLO`            => Some("TLS_ST_CR_SRVR_HELLO")
        case `TLS_ST_CR_CERT`                  => Some("TLS_ST_CR_CERT")
        case `TLS_ST_CR_COMP_CERT`             => Some("TLS_ST_CR_COMP_CERT")
        case `TLS_ST_CR_CERT_STATUS`           => Some("TLS_ST_CR_CERT_STATUS")
        case `TLS_ST_CR_KEY_EXCH`              => Some("TLS_ST_CR_KEY_EXCH")
        case `TLS_ST_CR_CERT_REQ`              => Some("TLS_ST_CR_CERT_REQ")
        case `TLS_ST_CR_SRVR_DONE`             => Some("TLS_ST_CR_SRVR_DONE")
        case `TLS_ST_CR_SESSION_TICKET`        => Some("TLS_ST_CR_SESSION_TICKET")
        case `TLS_ST_CR_CHANGE`                => Some("TLS_ST_CR_CHANGE")
        case `TLS_ST_CR_FINISHED`              => Some("TLS_ST_CR_FINISHED")
        case `TLS_ST_CW_CLNT_HELLO`            => Some("TLS_ST_CW_CLNT_HELLO")
        case `TLS_ST_CW_CERT`                  => Some("TLS_ST_CW_CERT")
        case `TLS_ST_CW_COMP_CERT`             => Some("TLS_ST_CW_COMP_CERT")
        case `TLS_ST_CW_KEY_EXCH`              => Some("TLS_ST_CW_KEY_EXCH")
        case `TLS_ST_CW_CERT_VRFY`             => Some("TLS_ST_CW_CERT_VRFY")
        case `TLS_ST_CW_CHANGE`                => Some("TLS_ST_CW_CHANGE")
        case `TLS_ST_CW_NEXT_PROTO`            => Some("TLS_ST_CW_NEXT_PROTO")
        case `TLS_ST_CW_FINISHED`              => Some("TLS_ST_CW_FINISHED")
        case `TLS_ST_SW_HELLO_REQ`             => Some("TLS_ST_SW_HELLO_REQ")
        case `TLS_ST_SR_CLNT_HELLO`            => Some("TLS_ST_SR_CLNT_HELLO")
        case `DTLS_ST_SW_HELLO_VERIFY_REQUEST` => Some("DTLS_ST_SW_HELLO_VERIFY_REQUEST")
        case `TLS_ST_SW_SRVR_HELLO`            => Some("TLS_ST_SW_SRVR_HELLO")
        case `TLS_ST_SW_CERT`                  => Some("TLS_ST_SW_CERT")
        case `TLS_ST_SW_COMP_CERT`             => Some("TLS_ST_SW_COMP_CERT")
        case `TLS_ST_SW_KEY_EXCH`              => Some("TLS_ST_SW_KEY_EXCH")
        case `TLS_ST_SW_CERT_REQ`              => Some("TLS_ST_SW_CERT_REQ")
        case `TLS_ST_SW_SRVR_DONE`             => Some("TLS_ST_SW_SRVR_DONE")
        case `TLS_ST_SR_CERT`                  => Some("TLS_ST_SR_CERT")
        case `TLS_ST_SR_COMP_CERT`             => Some("TLS_ST_SR_COMP_CERT")
        case `TLS_ST_SR_KEY_EXCH`              => Some("TLS_ST_SR_KEY_EXCH")
        case `TLS_ST_SR_CERT_VRFY`             => Some("TLS_ST_SR_CERT_VRFY")
        case `TLS_ST_SR_NEXT_PROTO`            => Some("TLS_ST_SR_NEXT_PROTO")
        case `TLS_ST_SR_CHANGE`                => Some("TLS_ST_SR_CHANGE")
        case `TLS_ST_SR_FINISHED`              => Some("TLS_ST_SR_FINISHED")
        case `TLS_ST_SW_SESSION_TICKET`        => Some("TLS_ST_SW_SESSION_TICKET")
        case `TLS_ST_SW_CERT_STATUS`           => Some("TLS_ST_SW_CERT_STATUS")
        case `TLS_ST_SW_CHANGE`                => Some("TLS_ST_SW_CHANGE")
        case `TLS_ST_SW_FINISHED`              => Some("TLS_ST_SW_FINISHED")
        case `TLS_ST_SW_ENCRYPTED_EXTENSIONS`  => Some("TLS_ST_SW_ENCRYPTED_EXTENSIONS")
        case `TLS_ST_CR_ENCRYPTED_EXTENSIONS`  => Some("TLS_ST_CR_ENCRYPTED_EXTENSIONS")
        case `TLS_ST_CR_CERT_VRFY`             => Some("TLS_ST_CR_CERT_VRFY")
        case `TLS_ST_SW_CERT_VRFY`             => Some("TLS_ST_SW_CERT_VRFY")
        case `TLS_ST_CR_HELLO_REQ`             => Some("TLS_ST_CR_HELLO_REQ")
        case `TLS_ST_SW_KEY_UPDATE`            => Some("TLS_ST_SW_KEY_UPDATE")
        case `TLS_ST_CW_KEY_UPDATE`            => Some("TLS_ST_CW_KEY_UPDATE")
        case `TLS_ST_SR_KEY_UPDATE`            => Some("TLS_ST_SR_KEY_UPDATE")
        case `TLS_ST_CR_KEY_UPDATE`            => Some("TLS_ST_CR_KEY_UPDATE")
        case `TLS_ST_EARLY_DATA`               => Some("TLS_ST_EARLY_DATA")
        case `TLS_ST_PENDING_EARLY_DATA_END`   => Some("TLS_ST_PENDING_EARLY_DATA_END")
        case `TLS_ST_CW_END_OF_EARLY_DATA`     => Some("TLS_ST_CW_END_OF_EARLY_DATA")
        case `TLS_ST_SR_END_OF_EARLY_DATA`     => Some("TLS_ST_SR_END_OF_EARLY_DATA")
        case _                                 => _root_.scala.None
    extension (a: OSSL_HANDSHAKE_STATE)
      inline def &(b: OSSL_HANDSHAKE_STATE): OSSL_HANDSHAKE_STATE = a & b
      inline def |(b: OSSL_HANDSHAKE_STATE): OSSL_HANDSHAKE_STATE = a | b
      inline def is(b: OSSL_HANDSHAKE_STATE): Boolean = (a & b) == b
