name: ci

on:
  push:
    branches:
      - main
  #   tags:
  #     - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: # be able to manually trigger a workflow run

env:
  # SCALA_NEXT_VERSION: "3.8.2"
  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - "11"
          - "17"
          - "21"
          - "25"
    steps:
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
      - uses: actions/checkout@v6

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - uses: coursier/cache-action@v7
      - uses: coursier/setup-action@v2
        with:
          apps: mill

      - name: Run tests for curl bindings
        run: |
          ./mill show modules.curl.nativeLinkingOptions
          ./mill modules.curl.test

      - name: Run tests for openssl bindings
        run: |
          ./mill show modules.openssl.nativeLinkingOptions
          ./mill modules.openssl.test

      - name: Run tests for Java HTTP Client
        run: |
          ./mill modules.java-http-client.test
          ./mill modules.java-http-client.test-internal

      - name: Run tests for Java HTTP Client on JVM
        run: |
          ./mill modules.java-http-client.jvm.test

  test-windows:
    runs-on: windows-latest
    needs:
      - test-linux
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows # x64-windows-static
      VCPKG_ROOT: "${{ github.workspace }}\\vcpkg"
      VCPKG_INSTALLED_DIR: "${{ github.workspace }}\\vcpkg\\installed"
      VCPKG_COMMIT_ID: "66c0373dc7fca549e5803087b9487edfe3aca0a1" # vcpkg 2026.01.16 Release
    strategy:
      fail-fast: false
      matrix:
        java: # only test one JVM version before we have caching for vcpkg
          # - "11"
          # - "17"
          # - "21"
          - "25"
    steps:
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
      - uses: actions/checkout@v6

      - id: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: "${{ env.VCPKG_COMMIT_ID }}"
          runVcpkgInstall: true
          doNotCache: false

      - uses: coursier/cache-action@v7
      - uses: coursier/setup-action@v2
        with:
          apps: mill

      - name: Run tests for curl bindings
        env:
          SCALANATIVE_INCLUDE_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\include"
          SCALANATIVE_LIB_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\lib"
        run: |
          .\mill show modules.curl.nativeLinkingOptions
          .\mill modules.curl.test

      - name: Run tests for openssl bindings
        env:
          SCALANATIVE_INCLUDE_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\include"
          SCALANATIVE_LIB_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\lib"
        run: |
          .\mill show modules.openssl.nativeLinkingOptions
          .\mill modules.openssl.test

      - name: Run tests for Java HTTP Client
        env:
          SCALANATIVE_INCLUDE_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\include"
          SCALANATIVE_LIB_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\lib"
        run: |
          .\mill modules.java-http-client.test
          .\mill modules.java-http-client.test-internal

      - name: Run tests for Java HTTP Client on JVM
        env:
          SCALANATIVE_INCLUDE_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\include"
          SCALANATIVE_LIB_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\lib"
        run: |
          .\mill modules.java-http-client.jvm.test

  publish-sonatype:
    if: github.repository == 'lqhuang/scala-native-http' && contains(github.ref, 'refs/tags/')
    needs:
      - test-linux
      - test-windows
    runs-on: ubuntu-latest
    env:
      SONATYPE_PGP_PRIVATE_KEY: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY }}
      SONATYPE_PGP_PRIVATE_KEY_PASSWORD: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY_PASSWORD }}
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
      - uses: coursier/cache-action@v7
      - uses: coursier/setup-action@v2
        with:
          apps: mill

      - name: Publish to Maven Central
        run: |
          if [[ $(git tag --points-at HEAD) != '' ]]; then
            echo $SONATYPE_PGP_PRIVATE_KEY | base64 --decode > gpg_key
            gpg --import --no-tty --batch --yes gpg_key
            rm gpg_key
            ./mill -i mill.scalalib.PublishModule/publishAll \
              --sonatypeCreds $SONATYPE_USER:$SONATYPE_PASSWORD \
              --gpgArgs --passphrase=$SONATYPE_PGP_PRIVATE_KEY_PASSWORD,--no-tty,--pinentry-mode,loopback,--batch,--yes,-a,-b \
              --publishArtifacts __.publishArtifacts \
              --readTimeout 600000 \
              --awaitTimeout 600000 \
              --release true \
              --signed true
          fi
      - name: Create GitHub Release
        id: create_gh_release
        # WARN: `actions/create-release` is currently unmaintained. It just works now, keep it until it breaks.
        uses: actions/create-release@v1.1.4
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          # body:
          draft: false
